"""empty message

Revision ID: 1551f6be2d5d
Revises: bf0dcb875183
Create Date: 2023-10-02 13:44:47.586435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1551f6be2d5d'
down_revision = 'bf0dcb875183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vyrobek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('vyrobce_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vyrobce_id'], ['vyrobce.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vyrobek')
    # ### end Alembic commands ###
